### ISSUE TITLE
cannot load devices

### ISSUE THREAD

**Issue by lesjaw** [marvinroger/homie-server#10]
i edit the infrastructure.yml

```
devices:
  - id: 811c09e0
    location: Olmatix House
    nodes:
      - type: light
        id: switch
        name: Lampu Kamar     
  - id: 80be27e0
    location: Olmatix House
    nodes:
      - type: light
        id: switch
        name: Lampu Teras
groups:
  - id: first-floor
    name: First floor
    devices:
      - 811c09e0
      - 80be27e0
```

but GUI give me empty devices, no devices at all and homie console gave me no error output log..
i have success using openhab item with this..

```
Switch  Light1      ""      <light> { mqtt=">[broker:devices/811c09e0/light/on/set:command:ON:true],    >[broker:devices/811c09e0/light/on/set:command:OFF:false]" }
String  Status1 "[%s]"  <network>   { mqtt="<[broker:devices/811c09e0/$online:state:Online:true],       <[broker:devices/811c09e0/$online:state:Offline:false]" }
String  IP1 "[%s]"  <network>       { mqtt="<[broker:devices/811c09e0/$localip:state:default]" }
String  Signal1 "[%s]"  <network>   { mqtt="<[broker:devices/811c09e0/$signal:state:default]" }
Switch  Light2      ""      <light> { mqtt=">[broker:devices/80be27e0/light/on/set:command:ON:true],    >[broker:devices/80be27e0/light/on/set:command:OFF:false]" }
String  Status2 "[%s]"  <network>   { mqtt="<[broker:devices/80be27e0/$online:state:Online:true],       <[broker:devices/80be27e0/$online:state:Offline:false]" }
String  IP2 "[%s]"  <network>       { mqtt="<[broker:devices/80be27e0/$localip:state:default]" }
String  Signal2 "[%s]"  <network>   { mqtt="<[broker:devices/80be27e0/$signal:state:default]" }
```

can you tell me what is exactly wrong in my infrastructure.yml?
